### ISSUE TITLE
1password.pkg.recipe hardcoded to 1password 4

### ISSUE THREAD

**Issue by hilljgo** [autopkg/justinrummel-recipes#13]
The following lines cause autopkg to fail. Its hardcoded to an old version of 1password, while autopkg will download the newest version of 1password (currently version 6). Any way to make this field dynamic? Of course manually changing it to `1Password 6.app` will fix it but I thought for future use this could be dynamic.

```
 <key>input_plist_path</key>
                <string>%pkgroot%/Applications/1Password 4.app/Contents/Info.plist</string>
```

autopkg gives the error:

```
The following recipes failed:
    1Password.pkg.recipe
        Error in com.justinrummel.pkg.1Password: Processor: Versioner: Error: File '/Users/.../Library/AutoPkg/Cache/com.justinrummel.pkg.1Password/1Password/Applications/1Password 4.app/Contents/Info.plist' does not exist or could not be read.
```

**Comment by justinrummel** [comment]
I'll look at it this afternoon.

**Comment by justinrummel** [comment]
Updated to use Version variable.  When v7 comes out, updating with a pull request will be possible.
