### ISSUE TITLE
Permissions issue after install

### ISSUE THREAD

**Issue by peterkelm** [autopkg/justinrummel-recipes#20]
You recipe did not work in our environment initially as it did not assign proper permissions. As a consequence, Fusion failed to launch with this error: "VMware Fusion is damaged and could not be repaired"

I searched the web and found below script (that seems to be from you but isn't included in your recipe here). Added this as a postinstall script fixed the issue.
```
#!/bin/bash
#
# Pinched with <3 from: https://github.com/autopkg/justinrummel-recipes/blob/42bc13881fe373f771cefec20a53d7844172019f/VMware%20Fusion/VMwareFusion.pkg.munki.recipe
#

if [ -e /Applications/VMware\ Fusion.app/Contents/Library/Initialize\ VMware\ Fusion.tool ]
then
        /Applications/VMware\ Fusion.app/Contents/Library/Initialize\ VMware\ Fusion.tool set
fi
```

**Comment by justinrummel** [comment]
I find it odd that this is the first reporting of this issue in one 3yrs.  I don't admin Apple environments anymore, so if you se a fix within the actual recipe then I would suggest you add this as a post install script.

**Comment by peterkelm** [comment]
For now we solved the issue via a manual addition of that postinstall script (as you suggested). Will try to put a pull request together within the week...

**Comment by justinrummel** [comment]
Resolving since we are able to use the post-install script.
