### ISSUE TITLE
JSS recipes use non-standard key names

### ISSUE THREAD

**Issue by grahampugh** [autopkg/justinrummel-recipes#21]
Hi Justin

I'm trying to help troubleshoot a new user of JSSImporter who is trying to use your TeamViewer recipe. I notice it has some non-standard keys in it that normal users would not be able to use without having access to different Policy Templates. 

I would advise removing this recipe to a private repo if you are still using it, or in any case deprecating it.

**Comment by justinrummel** [comment]
Happy to review a PR.

**Comment by grahampugh** [comment]
Very well, see #22

**Comment by justinrummel** [comment]
approved changes
